image: maven:3-jdk-11
before_script:
  - apt-get update -qq && apt-get install

cache:
  key: "maven3"
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

stages:
  - build

maven_job:
  stage: build
  script:
    - mvn clean package

